[package]
name = "psi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
thiserror.workspace = true

psi-map = { path = "../psi-map" }
