[package]
name = "psi-map"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
either.workspace = true
enum-map.workspace = true
thiserror.workspace = true
